version: '3.8'

services:
  lunarv:
    build:
      context: .
      dockerfile: Dockerfile.website
    ports:
      - "80:80"
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0

  # Optional: Add a database for storing results
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: lunarv
      POSTGRES_USER: lunarv_user
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: